# Generated by Django 5.0.4 on 2026-05-27 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel and Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('source_row_reference', models.CharField(blank=True, max_length=100)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=100)),
                ('activity_description', models.TextField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity_original', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit_original', models.CharField(blank=True, max_length=20)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=20)),
                ('conversion_applied', models.TextField(blank=True)),
                ('emission_factor_used', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=50)),
                ('emission_factor_source', models.CharField(blank=True, max_length=100)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('flags', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_emissions', to=settings.AUTH_USER_MODEL)),
                ('raw_ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_emissions', to='ingestion.rawingestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='EmissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.normalizedemission')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
    ]
